#!/bin/bash

export PHONEGAP_TOKEN="XXXXXXXXXXXXXXXXXXXX"
export PHONEGAP_APP_ID="0000000"
export PHONEGAP_ANDROID_KEY_ID="000000"
export PHONEGAP_ANDROID_KEY_PASSWORD="password"
export PHONEGAP_ANDROID_KEYSTORE_PASSWORD="password"
export PHONEGAP_IOS_KEY_ID="000000"
export PHONEGAP_IOS_KEY_PASSWORD="password"
